### ISSUE TITLE
Unknown option "--enable-sand"

### ISSUE THREAD

**Issue by rstanislav** [cgutman/moonlight-packaging#1]
Hello! trying to compile latest git version on RPi 4 with RPiOS bullseye with build-dep.sh script(installed all needed depencies) - all is good to the step with ffmpeg - configure says that it don't know all these modules:

--disable-rpi --enable-sand --enable-libudev --enable-v4l2-request --enable-hwaccel=h264_v4l2request --enable-hwaccel=hevc_v4l2request

Thanks for help!

**Comment by cgutman** [comment]
Make sure you're building `FFmpeg-rpi`. It has some special patches for HEVC that you need.

**Comment by rstanislav** [comment]
Fixed, thanks! I cloned wrong branch.
It working, got about ~300fps on 1080p HEVC, on h264 performance is way worse, about 58-59fps.
